# Generated by Django 5.1.6 on 2025-02-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswers',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='total_questions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Questions'),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='quizzes.answer', verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_question', to='quizzes.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='user_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_details', to='users.userresponse', verbose_name='User Response'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended At'),
        ),
    ]
